from odoo import fields, models

from odoo import api

from zeep import Client



class AddressBook(models.Model):
    _name = 'address.book'
    _description = 'Address Book Master'

    name = fields.Char('name')
    entityId = fields.Char('AN8')
    entityTypeCode = fields.Char('AddressType1')
    personCorporationCode = fields.Char('PersonCorporationCode')
    subledgerInactiveCode = fields.Char('SubledgerInactiveCode')
    entityTaxIdAdditional = fields.Char('TaxId2')
    taxExemptCertificate = fields.Char('CertificateTaxExempt')
    isEntityType3 = fields.Char('AddressType3')
    isEntityType4 = fields.Char('AddressType4')
    isEntityType5 = fields.Char('AddressType5')
    businessUnit = fields.Char('CostCenter')
    employeeGroupApprovalsCode = fields.Char('EmployeeGroupApprovals')
    entityIdRelated1 = fields.Char('AddressNumber1st')
    entityIdRelated2 = fields.Char('AddressNumber2nd')
    entityIdRelated3 = fields.Char('AddressNumber3rd')
    entityIdRelated4 = fields.Char('AddressNumber4th')
    entityIdRelated5 = fields.Char('AddressNumber5th')
    entityIdRelated6 = fields.Char('AddressNumber6th')
    mailingName = fields.Char('NameMailing')
    stateCode = fields.Char('State')
    countryCode = fields.Char('Country')
    mailingNameSecondary = fields.Char('SecondaryMailingName')
    addressLine1 = fields.Char('AddressLine1')
    addressLine2 = fields.Char('AddressLine2')
    addressLine3 = fields.Char('AddressLine3')
    addressLine4 = fields.Char('AddressLine4')
    postalCode = fields.Char('ZipCodePostal')
    city = fields.Char('City')
    countyCode = fields.Char('CountyAddress')
    categoryCode001 = fields.Char('ReportCodeAddBook001')
    categoryCode010 = fields.Char('ReportCodeAddBook010')
    categoryCode011 = fields.Char('ReportCodeAddBook011')
    categoryCode012 = fields.Char('ReportCodeAddBook012')
    categoryCode013 = fields.Char('ReportCodeAddBook013')
    categoryCode014 = fields.Char('ReportCodeAddBook014')
    categoryCode015 = fields.Char('ReportCodeAddBook015')
    categoryCode016 = fields.Char('ReportCodeAddBook016')
    categoryCode017 = fields.Char('ReportCodeAddBook017')
    categoryCode018 = fields.Char('ReportCodeAddBook018')
    categoryCode019 = fields.Char('ReportCodeAddBook019')
    categoryCode002 = fields.Char('ReportCodeAddBook002')
    categoryCode020 = fields.Char('ReportCodeAddBook020')
    categoryCode021 = fields.Char('CategoryCodeAddressBook2')
    categoryCode022 = fields.Char('CategoryCodeAddressBk22')
    categoryCode023 = fields.Char('CategoryCodeAddressBk23')
    categoryCode024 = fields.Char('CategoryCodeAddressBk24')
    categoryCode025 = fields.Char('CategoryCodeAddressBk25')
    categoryCode026 = fields.Char('CategoryCodeAddressBk26')
    categoryCode027 = fields.Char('CategoryCodeAddressBk27')
    categoryCode028 = fields.Char('CategoryCodeAddressBk28')
    categoryCode029 = fields.Char('CategoryCodeAddressBk29')
    categoryCode003 = fields.Char('ReportCodeAddBook003')
    categoryCode030 = fields.Char('CategoryCodeAddressBk30')
    categoryCode004 = fields.Char('ReportCodeAddBook004')
    categoryCode005 = fields.Char('ReportCodeAddBook005')
    categoryCode006 = fields.Char('ReportCodeAddBook006')
    categoryCode007 = fields.Char('ReportCodeAddBook007')
    categoryCode008 = fields.Char('ReportCodeAddBook008')
    categoryCode009 = fields.Char('ReportCodeAddBook009')
    classificationCode001 = fields.Char('ClassificationCode01')
    classificationCode002 = fields.Char('ClassificationCode02')
    classificationCode003 = fields.Char('ClassificationCode03')
    classificationCode004 = fields.Char('ClassificationCode04')
    classificationCode005 = fields.Char('ClassificationCode05')
    userReservedCode = fields.Char('UserReservedCode')
    userReservedNumber = fields.Integer('UserReservedNumber')
    userReservedReference = fields.Char('UserReservedReference')
    numberOfEmployees = fields.Integer('NumberOfEmployee')
    rateGrowth = fields.Integer('GrowthRate')
    revenueRangeCode = fields.Char('RevenueRange')
    yearCompanyFounded = fields.Char('YearStarted')
    dunBradStreetId = fields.Char('DUNSNumber')
    glBankAccount = fields.Char('GlBankAccount')
    stockTickerSymbol = fields.Char('Ticker')
    stockExchange = fields.Char('StockExchange')
    entityName = fields.Char('NameAlpha')
    entityIdParent = fields.Char('AddressNumberParent')
    parentStructureTypeCode = fields.Char('OrganizationTypeStructur')
    contactId = fields.Integer('LineNumberID')
    phoneLineNumber = fields.Integer('SequenceNumber70')
    relatedPersonId = fields.Integer('ContactPersonalID')
    phoneTypeCode = fields.Char('PhoneNumberType')
    areaCode = fields.Char('PhoneAreaCode1')
    phoneNumber = fields.Char('PhoneNumber')
    electronicAddressLineNumber = fields.Integer('SequenceNumber70')
    electronicAddressTypeCode = fields.Char('ElectronicAddressType')
    electronicAddress = fields.Char('EmailAddressow')
    electronicAddressClassificationCode = fields.Char('EmailClassification')
    messageIndicatorCode = fields.Integer('EmailHierarchy')
    entityNameSecondary = fields.Char('NameAlpha')
    languageCode = fields.Char('LanguagePreference')
    industryClassificationCode = fields.Char('StandardIndustryCode')
    remark = fields.Char('NameRemark')
    description1 = fields.Char('DescripCompressed')
    creditMessageCode = fields.Char('CreditMessage')
    entityLongId = fields.Char('Long Address Number')
    entityTaxId = fields.Char('Tax Id')

